### ISSUE TITLE
Payment webhook failing with default Mollie module installed but disabled

### ISSUE THREAD

**Issue by Rhytz** [NullCrayfish/wefact-mollie-payment-method-modules#1]
The readme mentions 

> **Each module requires the by default included mollie module to be present (may be deactivated) as the new classes extend the mollie class**

But when the default module is disabled, users will receive the following error after their payment, and the webhook will not succeed, resulting in the invoice not being marked as paid:

> error loading configuration
payment provider configuration not found in database

**Comment by nicksulkers** [comment]
I believe the modules have to be activated once to add some entries to the database. Once that's done they can be disabled.
