### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by jeroenedig** [NullCrayfish/wefact-mollie-payment-method-modules#3]
Allereerst bedankt voor het beschikbaar stellen! 👍 

Helaas werkt het niet als Mollie van Hostfact zelf actief is (wat op zich niet erg is, want dat is wel te doen).

Verder krijg ik op alle opties van deze modules error 500 doe ik iets fout of gaat het in de afhandeling niet ok?

Dit gebeurd bij alle betaalmethodes (iDeal, Bancontact enz). De API key zelf is ok, want deze werkt wel als we het direct doen via de Hostfact Mollie module. 

De betaling zelf gaat ook goed, alleen de afhandeling (het doorsturen van een 'OK' (webhook) geeft een error 500. 

---

Wat kan ik doen om dit op te lossen?

---

Error: 

[Wed May 23 23:42:07.369676 2018] [php7:error] [pid 23663] [client 77.172.154.38:53178] PHP Fatal error:  Uncaught Mollie_API_Exception: Error executing API call (request): Incorrect API key. This API key does not belong to this payment's profile.. in /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php:229\nStack trace:\n#0 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(91): Mollie_API_Resource_Base->performApiCall('GET', 'payments/tr_Wgd...')\n#1 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(192): Mollie_API_Resource_Base->rest_read('payments', 'tr_WgdzT4u3zR')\n#2 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/payment_provider.php(136): Mollie_API_Resource_Base->get('tr_WgdzT4u3zR')\n#3 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/return.php(13): mollie->validateTransaction('tr_WgdzT4u3zR')\n#4 {main}\n  thrown in /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php on line 229

**Comment by nicksulkers** [comment]
Hoi Jeroen,

Een probleem met de API key zou vermoedelijk al optreden voordat de betaling verricht kan worden. De error doet wel vermoeden dat het een probleem is met de mollie instellingen.

> Incorrect API key. This API key does not belong to this payment's profile.

Kun je bevestigen of de betaalmethodes naar behoren geactiveerd zijn op mollie.nl?
Werkt het eventueel wel met je test api key?

**Comment by RKorting** [comment]
Vraagstuk is afgehandeld. De 'Mollie API key' was niet ingevuld, maar een partner id.

**Comment by jeroenedig** [comment]
Dit vraagstuk is helaas nog niet afgehandeld (nu weer volop mee bezig)

[Tue Mar 26 08:47:29.186092 2019] [proxy_fcgi:error] [pid 1499:tid 140715846985472] [client 77.172.154.38:57414] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Mollie_API_Exception: Error executing API call (request): Incorrect API key. This API key does not belong to this payment's profile.. in /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php:229\nStack trace:\n#0 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(91): Mollie_API_Resource_Base->performApiCall('GET', 'payments/tr_qrc...')\n#1 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/API/Resource/Base.php(192): Mollie_API_Resource_Base->rest_read('payments', 'tr_qrca4PAqDv')\n#2 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/payment_provider.php(136): Mollie_API_Resource_Base->get('tr_qrca4PAqDv')\n#3 /home/hosting/domains/premier.hosting/public_html/klantenpaneel/betalen/mollie/return.php(13): mollie->validateTransaction('tr_qrca4PAqDv')\n#4 {main}\n  thrown in /home/hosting/domains/premier.hosting/public_html/...\n', referer: https://www.mollie.com/paymentscreen/banktransfer/reference/ls0dz5

In dit geval de Mollie banktransfer bij zowel live als test API key gaat het fout.

Kortom alles gaat goed tot ik de betaling voltooi dan krijg ik de server error / 500.
